### ISSUE TITLE
Unable to get a name server on Jhub

### ISSUE THREAD

**Issue by iperezx** [national-data-platform/ndp#23]
I think the error is that it can't find the pvc with the name server.

Error log:
```
Spawn failed: (422) Reason: error HTTP response headers: <CIMultiDictProxy('Audit-Id': '56863aec-3994-4c6f-a66d-f7dc674b4340', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '5d8b88e8-3799-4126-9528-48f2d3ddf6cc', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'a3e2ebab-2463-4309-98ea-34fb239007c6', 'Date': 'Tue, 27 Feb 2024 16:58:33 GMT', 'Content-Length': '503')> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"{pod}\" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: \"volume-{name server}\"","reason":"Invalid","details":{"name":"jupyter-{pod}","kind":"Pod","causes":[{"reason":"FieldValueNotFound","message":"Not found: \"volume-{name server}\"","field":"spec.initContainers[0].volumeMounts[0].name"}]},"code":422}
```

Action items:
1. check the steps it takes to look for the pvc. Example: volume-{user}{name server}
2. check the db

**Comment by sergeygurvich** [comment]
Updade on this:
This code was causing the issue:
```   
initContainers:
    - name: volume-permissions
      image: busybox
      command: ["sh", "-c", "chmod 777 /srv/starter_content/data"]
      volumeMounts:
      - mountPath: /srv/starter_content/data
        name: volume-{username}{servername}
```

We take care of permissions in Dockerfile of the images, so I removed this initContainers, and the original error doesn't appear anymore.

However, now there is another error:
```
2024-02-29T16:34:49Z [Warning] Multi-Attach error for volume "pvc-f41aa06a-7b51-4bcc-b3e6-dffd34c927d9" Volume is already used by pod(s) jupyter-segurvich-40ucsd-2eedu--server1
2024-02-29T16:36:52Z [Warning] Unable to attach or mount volumes: unmounted volumes=[volume-segurvich-40ucsd-2eedu], unattached volumes=[volume-segurvich-40ucsd-2eedu]: timed out waiting for the condition
```

It doesn't happen all the time. Sometimes I'm able to spawn up to 3 named servers
